name:                cornelis
version:             0.2.0.1
github:              "isovector/cornelis"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/cornelis#readme>

dependencies:
- base >= 4.7 && < 5
- nvim-hs >= 2.2.0.3 && < 3
- nvim-hs-contrib >= 2.0 && < 3
- containers
- async
- process
- mtl
- lens >= 4.19.2
- generic-lens >= 2.1.0.0
- transformers
- filepath
- directory
- aeson >= 1.5.6.0
- unliftio-core >= 0.2.0.1
- unagi-chan >= 0.4.1.3
- resourcet >= 1.2.4.3
- text
- bytestring
- fingertree >= 0.1.4.2
- prettyprinter >= 1.7.1 && < 2
- vector
- random
- megaparsec >= 9.0.1 && < 10
- diff-loc >= 0.1.0.0

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - LambdaCase
  - KindSignatures
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  # - NamedWildCards
  - NumericUnderscores
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TraditionalRecordSyntax
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  cornelis:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cornelis

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cornelis
    - hspec
    - temporary
    - filepath
    - QuickCheck >= 2.14.2
    - levenshtein >= 0.1.3.0

    # build-dependencies:
    # - hspec-discover

data-files:
  # Include Agda files needed for tests
  - test/*.agda
